version: "3"

services:

  mysql:
      image: docker.io/bitnami/mysql:8.0
      volumes:
        - $PWD/conf.d/my.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
        - mysql-data:/bitnami/mysql/data
        - /etc/localtime:/etc/localtime:ro
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
        - MYSQL_REPLICATION_USER=repl_user_fws
        - MYSQL_REPLICATION_PASSWORD=FWS@123
        - TZ=Asia/Ho_Chi_Minh
        - MYSQL_ROOT_PASSWORD=Flick123
        - log-bin=mysql-bin
        - binlog-format=ROW
      restart: always
      ports:
        - '3306:3306'
      healthcheck:
        test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
        interval: 15s
        timeout: 5s
        retries: 6


  radius:
    container_name: radius
    build:
      context: .
      dockerfile: Dockerfile-freeradius
    restart: unless-stopped
    depends_on: 
      - mysql
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Flick123
      # Optional settings
      - DEFAULT_CLIENT_SECRET=testing123
    volumes:
      - ./data/freeradius:/data
    # If you want to disable debug output, remove the command parameter
    command: -X

  radius-web:
    build: .
    container_name: radius-web
    restart: unless-stopped
    depends_on:
      - radius
      - mysql
    ports:
      - '80:80'
      - '8000:8000'
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Flick123
      # Optional Settings:
      - DEFAULT_CLIENT_SECRET=testing123
      - DEFAULT_FREERADIUS_SERVER=radius
      - MAIL_SMTPADDR=127.0.0.1
      - MAIL_PORT=25
      - MAIL_FROM=root@daloradius.xdsl.by
      - MAIL_AUTH=

    volumes:
      - ./data/daloradius:/data

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ./data/mysql
